AllCops:
  NewCops: enable
  DisabledByDefault: false

Layout/IndentationWidth:
  Enabled: false
  # Number of spaces for each indentation level.
  # Width: 2

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/FirstArgumentIndentation:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/AccessModifierIndentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false


