AllCops:
  NewCops: enable
  DisabledByDefault: false

Layout/IndentationWidth:
  Enabled: false
  # Number of spaces for each indentation level.
  # Width: 2

Style/FrozenStringLiteralComment:
  Enabled: false
