# DB configuration

default: &default
    pool: 30
    host: 127.0.0.1
    adapter: postgresql
    encoding: unicode
    reconnect: false

development:
    <<: *default
    database: <%= Rails.application.credentials.db[:database] %>
    username: <%= Rails.application.credentials.db[:username] %>
    password: <%= Rails.application.credentials.db[:password] %>
    port: <%= Rails.application.credentials.db.dig(:port) || 5432 %>

test:
    <<: *default
    database: <%= Rails.application.credentials.db[:database] %>
    username: <%= Rails.application.credentials.db[:username] %>
    password: <%= Rails.application.credentials.db[:password] %>
    port: <%= Rails.application.credentials.db[:port] %>

production:
    <<: *default
    port: <%= Rails.application.credentials.db[:port] %>
    host: <%= Rails.application.credentials.db[:host] %>
    database: <%= Rails.application.credentials.db[:database] %>
    username: <%= Rails.application.credentials.db[:username] %>
    password: <%= Rails.application.credentials.db[:password] %>
