# This workflow will deploy the application
name: "Deploy"
on:
  push:
    branches: [ "production" ]
  workflow_dispatch:

jobs:
  rails-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Add or replace dependency steps here
      - name: Executing remote commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: "34.193.107.238"
          username: ubuntu
          key: ${{ secrets.VESTA_CI_SSH_KEY }}
          script: |
            cd ~
            echo "HOLA" >> test.txt
